services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8088:8088"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./src:/app/src
      - /app/node_modules
      - /app/dist

  redis:
    image: redis:7
    ports:
      - "6379:6379"