services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
    command: npm run start:prod

  redis:
    image: redis:7
    ports:
      - "6379:6379"