services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: courtmate_backend
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    # depends_on:
    #   - redis
    # volumes:
    #   - .:/app
    #   - /app/node_modules

#   redis:
#     image: redis:7
#     container_name: courtmate_redis
#     ports:
#       - "6379:6379"
#     volumes:
#       - redis_data:/data

# volumes:
#   redis_data:
