


export const TYPES = {

    //Repositories
    IUserRepository: Symbol.for('IUserRepository'),
    INotificationRepository: Symbol.for('INotificationRepository'),
    IBookingRepository: Symbol.for('IBookingRepository'),
    ITokenRepository: Symbol.for('ITokenRepository'),
    IReccurringRepository: Symbol.for('ReccurringRepository'),
    ISlotRepository: Symbol.for('ISlotRepository'),
    IPaymentRepository: Symbol.for('IPaymentRepository'),
    IConversationRepository: Symbol.for('IConversationRepository'),
    IMessageRepository: Symbol.for('IMessageRepository'),
    IReviewRepository: Symbol.for('IReviewRepository'),
    ICaseRepository: Symbol.for('ICaseRepository'),
    ISubscriptionRepository: Symbol.for('ISubscriptionRepository'),
    IFilterRepository: Symbol.for('IFilterRepository'),
    IWalletRepository : Symbol.for('IWalletRepository'),

    //Services
    IEmailService: Symbol.for('IEmailService'),
    EmailConfig: Symbol.for('EmailConfig'),
    NotificationService: Symbol.for('NotificationService'),
    JwtTokenService: Symbol.for('JwtTokenService'),
    HashPasswordService: Symbol.for('HashPasswordService'),
    PaymentService: Symbol.for('PaymentService'),
    BookingExpirationJob: Symbol.for('BookingExpirationJob'),
    IRedisService: Symbol.for('IRedisService'),
    Server: Symbol.for('Server'),
    SocketIOServer: Symbol.for('SocketIOServer'),
    SocketIOService: Symbol.for('SocketIOService'),
    ReminderSchedulerService: Symbol.for('ReminderSchedulerService'),
    PassportService: Symbol.for('PassportService'),
    MulterService: Symbol.for('MulterService'),
    S3Service: Symbol.for('S3Service'),
    Logger: Symbol.for('Logger'),


    //Use Cases
    IGetAdminDashboard: Symbol.for('IGetAdminDashboardRepo'),
    IGetAllAdvocates: Symbol.for('IGetAllAdvocates'),
    IGetAllUsers: Symbol.for('IGetAllUsers'),
    IUpdateAdvocateStatus: Symbol.for('IUpdateAdvocateStatus'),
    IFindUser: Symbol.for('IFindUser'),
    IGetAdvocateDashboard: Symbol.for('IGetAdvocateDashboard'),
    IGetAdvocateDetails: Symbol.for('IGetAdvocateDetails'),
    IUpdateAdvocate: Symbol.for('IUpdateAdvocate'),
    IUpdateAdvocateProfile: Symbol.for('IUpdateAdvocateProfile'),
    IForgotPasswordSendMail: Symbol.for('IForgotPasswordSendMail'),
    IGoogleAuth: Symbol.for('IGoogleAuth'),
    ILoginUser: Symbol.for('ILoginUser'),
    IRefreshTokenUseCase: Symbol.for('IRefreshTokenUseCase'),
    IResetForgotPassword: Symbol.for('IResetForgotPassword'),
    ISignupUser: Symbol.for('ISignupUser'),
    IVerifyEmail: Symbol.for('IVerifyEmail'),
    IVerifyForgotPasswordMail: Symbol.for('IVerifyForgotPasswordMail'),
    IBookSlot: Symbol.for('IBookSlot'),
    IGetBookingThisHourUseCase: Symbol.for('IGetBookingThisHour'),
    IGetBookSlot: Symbol.for('IGetBookSlot'),
    IGetCallHistoryUseCase: Symbol.for('IGetCallHistoryUseCase'),
    IPostpone: Symbol.for('IPostpone'),
    IVerifyRoom: Symbol.for('IVerifyRoom'),
    ICreateCaseUseCase: Symbol.for('ICreateCaseUseCase'),
    IDeleteCaseUseCase: Symbol.for('IDeleteCaseUseCase'),
    IGetAllCasesUseCase: Symbol.for('IGetAllCasesUseCase'),
    IUpdateCaseUseCase: Symbol.for('IUpdateCaseUseCase'),
    IUpdateHearingUsecase: Symbol.for('IUpdateHearingUsecase'),
    ICreateConversation: Symbol.for('ICreateConversation'),
    ICreateMessage: Symbol.for('ICreateMessage'),
    IGetConversation: Symbol.for('IGetConversation'),
    IGetMessages: Symbol.for('IGetMessages'),
    IUpdateMessageStatus: Symbol.for('IUpdateMessageStatus'),
    IAddRecurringRule: Symbol.for('IAddRecurringRule'),
    IGetRecurringRules: Symbol.for('IGetRecurringRules'),
    ICreateReview: Symbol.for('ICreateReview'),
    IDeleteReviewUseCase: Symbol.for('IDeleteReviewUseCase'),
    IGetReviews: Symbol.for('IGetReviews'),
    IUpdateReviewUseCase: Symbol.for('IUpdateReviewUseCase'),
    IAddSlot: Symbol.for('IAddSlot'),
    IGetSlots: Symbol.for('IGetSlots'),
    IPostponeSlot: Symbol.for('IPostponeSlot'),
    ICreateSubscriptionUseCase: Symbol.for('ICreateSubscriptionUseCase'),
    IGetAllSubscriptionsUseCase: Symbol.for('IGetAllSubscriptionsUseCase'),
    IGetSubscriptionUseCase: Symbol.for('IGetSubscriptionUseCase'),
    IGetAllUserAdvocates: Symbol.for('IGetAllUserAdvocates'),
    IGetSavedAdvocates: Symbol.for('IGetSavedAdvocates'),
    IResetPassword: Symbol.for('IResetPassword'),
    IToggleSavedAdvocate: Symbol.for('IToggleSavedAdvocate'),
    IToggleUser: Symbol.for('IToggleUser'),
    ITopRatedAdvocatesUseCase: Symbol.for('ITopRatedAdvocatesUseCase'),
    ICreateCheckoutSessionUseCase: Symbol.for('ICreateCheckoutSessionUseCase'),
    IGetAllNotification: Symbol.for('IgetAllNotification'),
    IMarkAllAsRead: Symbol.for('IMarkAllAsRead'),
    IMarkAsRead: Symbol.for('IMarkAsRead'),
    IPaymentUseCase: Symbol.for('IPaymentUsecase'),
    IGetAllAdminAdvocates: Symbol.for('IGetAllAdminAdvocates'),
    ILogoutUseCase: Symbol.for('ILogoutUseCase'),
    IGetAllFilter: Symbol.for('IGetAllFilter'),
    IAddFilter: Symbol.for('IAddFilter'),
    IAddCategory: Symbol.for('IAddCategory'),
    IDeleteCategory: Symbol.for('IDeleteCategory'),
    IDeleteFilter: Symbol.for('IDeleteFilter'),
    IAddCaseHearing: Symbol.for('IAddCaseHearing'),
    IGetCaseHearingRepo: Symbol.for('IGetCaseHearingRepo'),
    IUpdateCaseHearingDataRepo: Symbol.for('IUpdateCaseHearingDataRepo'),
    IDeleteCaseHearingRepo : Symbol.for('IDeleteCaseHearingRepo'),
    ICancelBookingRepo : Symbol.for('ICancelBookingRepo'),
    IGetWallet :Symbol.for('IGetWallet'),
    IUpdateUnreadCount : Symbol.for('IUpdateUnreadCount'),

    // Controllers
    AdvocateController: Symbol.for('AdvocateController'),
    NotificationController: Symbol.for('NotificationController'),
    AdminUserController: Symbol.for('AdminUserController'),
    advProfileController: Symbol.for('advProfileController'),
    UserController: Symbol.for('UserController'),
    AdminDashboardController: Symbol.for('AdminDashboardController'),
    AdvocateDashboardController: Symbol.for('AdvocateDashboardController'),
    AuthController: Symbol.for('AuthController'),
    BookingController: Symbol.for('BookingController'),
    CaseController: Symbol.for('CaseController'),
    ConversationController: Symbol.for('ConversationController'),
    PaymentController: Symbol.for('paymentController'),
    RecurringRuleController: Symbol.for('RecurringRuleController'),
    ReviewController: Symbol.for('ReviewController'),
    SlotController: Symbol.for('SlotController'),
    SubscriptionController: Symbol.for('SubscriptionController'),
    AdvProfileController: Symbol.for('AdvProfileController'),
    ChatFileController: Symbol.for('ChatFileController'),
    FilterController: Symbol.for('FilterController'),
    WalletController: Symbol.for('WalletController'),


    // Middleware
    AuthMiddleware: Symbol.for('AuthMiddleware'),
    AuthMiddlewareImpl: Symbol.for('AuthMiddlewareImpl'),
}   