


export const TYPES = {

    //Repositories
    UserRepository: Symbol.for('UserRepository'),
    NotificationRepository: Symbol.for('NotificationRepository'),
    BookingRepository: Symbol.for('BookingRepository'),
    TokenRepository: Symbol.for('TokenRepository'),
    ReccurringRepository: Symbol.for('ReccurringRepository'),
    SlotRepository: Symbol.for('SlotRepository'),
    PaymentRepository: Symbol.for('PaymentRepository'),
    ConversationRepository: Symbol.for('ConversationRepository'),
    MessageRepository: Symbol.for('MessageRepository'),
    ReviewRepository: Symbol.for('ReviewRepository'),
    CaseRepository: Symbol.for('CaseRepository'),
    SubscriptionRepository: Symbol.for('SubscriptionRepository'),

    //Services
    EmailService: Symbol.for('EmailService'),
    EmailConfig: Symbol.for('EmailConfig'),
    NotificationService: Symbol.for('NotificationService'),
    JwtTokenService: Symbol.for('JwtTokenService'),
    HashPasswordService: Symbol.for('HashPasswordService'),
    PaymentService: Symbol.for('PaymentService'),
    BookingExpirationJob: Symbol.for('BookingExpirationJob'),
    RedisService : Symbol.for('RedisService'),
    Server: Symbol.for('Server'),
    SocketIOServer: Symbol.for('SocketIOServer'),
    SocketIOService: Symbol.for('SocketIOService'),
    ReminderSchedulerService : Symbol.for('ReminderSchedulerService'),
    PassportService: Symbol.for('PassportService'),
    MulterService: Symbol.for('MulterService'),
    S3Service: Symbol.for('S3Service'),
    Logger: Symbol.for('Logger'),


    //Use Cases
    GetAdminDashboard: Symbol.for('GetAdminDashboard'),
    GetAllAdvocates: Symbol.for('GetAllAdvocates'),
    GetAllUsers: Symbol.for('GetAllUsers'),
    UpdateAdvocateStatus: Symbol.for('UpdateAdvocateStatus'),
    FindUser: Symbol.for('FindUser'),
    GetAdvocateDashboard: Symbol.for('GetAdvocateDashboard'),
    GetAdvocateDetails: Symbol.for('GetAdvocateDetails'),
    UpdateAdvocate: Symbol.for('UpdateAdvocate'),
    UpdateAdvocateProfile: Symbol.for('UpdateAdvocateProfile'),
    ForgotPasswordSendMail: Symbol.for('forgotPasswordSendMail'),
    GoogleAuth: Symbol.for('GoogleAuth'),
    LoginUser: Symbol.for('LoginUser'),
    RefreshTokenUseCase: Symbol.for('RefreshTokenUseCase'),
    ResetForgotPassword: Symbol.for('ResetForgotPassword'),
    SignupUser: Symbol.for('SignupUser'),
    VerifyEmail: Symbol.for('verifyEmail'),
    VerifyForgotPasswordMail: Symbol.for('VerifyForgotPasswordMail'),
    BookSlot: Symbol.for('BookSlot'),
    GetBookingThisHourUseCase: Symbol.for('GetBookingThisHourUseCase'),
    GetBookSlot: Symbol.for('GetBookSlot'),
    GetCallHistoryUseCase: Symbol.for('GetCallHistoryUseCase'),
    Postpone: Symbol.for('Postpone'),
    VerifyRoom: Symbol.for('VerifyRoom'),
    CreateCaseUseCase: Symbol.for('CreateCaseUseCase'),
    DeleteCaseUseCase: Symbol.for('DeleteCaseUseCase'),
    GetAllCasesUseCase: Symbol.for('GetAllCasesUseCase'),
    UpdateCaseUseCase: Symbol.for('UpdateCaseUseCase'),
    UpdateHearingHistoryUseCase: Symbol.for('UpdateHearingHistoryUseCase'),
    CreateConversationUseCase: Symbol.for('CreateConversationUseCase'),
    CreateMessageUseCase: Symbol.for('CreateMessageUseCase'),
    GetConversationsUseCase: Symbol.for('GetConversationsUseCase'),
    GetMessagesUseCase: Symbol.for('GetMessagesUseCase'),
    UpdateMessageStatusUseCase: Symbol.for('UpdateMessageStatusUseCase'),
    AddRecurringRule: Symbol.for('AddRecurringRule'),
    GetRecurringRulesByAdvocate: Symbol.for('GetRecurringRulesByAdvocate'),
    CreateReviewUseCase: Symbol.for('CreateReviewUseCase'),
    DeleteReviewUseCase: Symbol.for('DeleteReviewUseCase'),
    GetReviewsUseCase: Symbol.for('GetReviewsUseCase'),
    UpdateReviewUseCase: Symbol.for('UpdateReviewUseCase'),
    AddSlot: Symbol.for('AddSlot'),
    GetSlots: Symbol.for('GetSlots'),
    PostponeSlot: Symbol.for('PostponeSlot'),
    CreateSubscriptionUseCase: Symbol.for('CreateSubscriptionUseCase'),
    GetAllSubscriptionsUseCase: Symbol.for('GetAllSubscriptionsUseCase'),
    GetSubscriptionUseCase: Symbol.for('GetSubscriptionUseCase'),
    GetAllUserAdvocates: Symbol.for('GetAllUserAdvocates'),
    GetSavedAdvocates: Symbol.for('GetSavedAdvocates'),
    ResetPassword: Symbol.for('ResetPassword'),
    ToggleSavedAdvocate: Symbol.for('ToggleSavedAdvocate'),
    ToggleUser: Symbol.for('ToggleUser'),
    TopRatedAdvocatesUseCase: Symbol.for('TopRatedAdvocatesUseCase'),
    CreateCheckoutSessionUseCase: Symbol.for('CreateCheckoutSessionUseCase'),
    GetAllNotification: Symbol.for('getAllNotification'),
    MarkAllAsRead: Symbol.for('MarkAllAsRead'),
    MarkAsRead: Symbol.for('MarkAsRead'),
    PaymentUseCase: Symbol.for('PaymentUsecase'),
    GetAllAdminAdvocates: Symbol.for('GetAllAdminAdvocates'),
    LogoutUseCase: Symbol.for('LogoutUseCase'),

    // Controllers
    AdvocateController: Symbol.for('AdvocateController'),
    NotificationController: Symbol.for('NotificationController'),
    AdminUserController: Symbol.for('AdminUserController'),
    advProfileController: Symbol.for('advProfileController'),
    UserController: Symbol.for('UserController'),
    AdminDashboardController: Symbol.for('AdminDashboardController'),
    AdvocateDashboardController: Symbol.for('AdvocateDashboardController'),
    AuthController: Symbol.for('AuthController'),
    BookingController: Symbol.for('BookingController'),
    CaseController: Symbol.for('CaseController'),
    ConversationController: Symbol.for('ConversationController'),
    PaymentController: Symbol.for('paymentController'),
    RecurringRuleController: Symbol.for('RecurringRuleController'),
    ReviewController: Symbol.for('ReviewController'),
    SlotController: Symbol.for('SlotController'),
    SubscriptionController: Symbol.for('SubscriptionController'),
    AdvProfileController: Symbol.for('AdvProfileController'),
    ChatFileController: Symbol.for('ChatFileController'),

    // Middleware
    AuthMiddleware: Symbol.for('AuthMiddleware'),
    AuthMiddlewareImpl: Symbol.for('AuthMiddlewareImpl'),
}   